version: '3'

services:
  nginx:
    build: .
    ports:
      - "80:80"
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge